title: "Data разработка на Python"
logo: media/logo.png
author: ""

sphinx:
  config:
    language: ru
    html_show_copyright: false

# Force re-execution of notebooks on each build, ensures that the book is executed from scratch each time
execute:
  execute_notebooks: force
  allow_errors: true

launch_buttons:
  colab_url: "https://colab.research.google.com"
  thebe: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/maximkeremet/tinkoff-python-course
  path_to_book: book
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: false
  use_edit_page_button: true
