name: Build and Deploy Jupyter Book

on:
  push:
    branches:
      - main

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r ./book/requirements.txt
    - name: Build Jupyter Book
      run: |
        jupyter-book build ./book/
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        deploy_key: ${{ secrets.PRIVATE_KEY }}
        external_repository: maximkeremet/data-developer-in-python-course
        publish_branch: gh-pages
        publish_dir: ./book/_build/html/
        force_orphan: true


permissions:
  contents: write
